const state={started:false,doors:0,rooms:1,threat:0,opened:new Set()};
const CHAOS_LIMIT=8;
let audioCtx=null,masterGain=null,musicGain=null,musicTimer=null;
const $=s=>document.querySelector(s);
const doorNames=['USCITA','NON ENTRARE','QUASI','DIETRO DI TE','IL PUBBLICO','NESSUNO','ANCORA','ELEONORA'];
const whispers=['Non tutte le porte vogliono essere aperte.','Hai sentito una risata o l’hai immaginata?','La stanza ricorda il tuo modo di scegliere.','Una porta in più. Perché?','Shaco non è davanti a te.','Quella porta non c’era prima.','Il corridoio sta imparando.'];
function ensureAudio(){if(audioCtx)return;audioCtx=new(window.AudioContext||window.webkitAudioContext)();masterGain=audioCtx.createGain();masterGain.gain.value=.18;masterGain.connect(audioCtx.destination)}
function tone(freq,duration,type='sine',gain=.035,when=0){if(!audioCtx)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.0001,audioCtx.currentTime+when);g.gain.exponentialRampToValueAtTime(gain,audioCtx.currentTime+when+.015);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+when+duration);o.connect(g);g.connect(masterGain);o.start(audioCtx.currentTime+when);o.stop(audioCtx.currentTime+when+duration+.03)}
function circusBell(){ensureAudio();tone(660,.7,'sine',.045);tone(990,.55,'sine',.028,.04);tone(1320,.35,'sine',.018,.09)}
function startCircusMusic(){ensureAudio();if(musicTimer)return;musicGain=audioCtx.createGain();musicGain.gain.value=.055;musicGain.connect(masterGain);const low=audioCtx.createOscillator(),drone=audioCtx.createOscillator(),lfo=audioCtx.createOscillator(),lfoGain=audioCtx.createGain();low.type='triangle';low.frequency.value=110;drone.type='sine';drone.frequency.value=55;lfo.frequency.value=4.2;lfoGain.gain.value=.035;lfo.connect(lfoGain);lfoGain.connect(musicGain.gain);low.connect(musicGain);drone.connect(musicGain);low.start();drone.start();lfo.start();const notes=[196,233,262,233,174,196,220,196];let i=0;musicTimer=setInterval(()=>{if(!audioCtx)return;const n=notes[i++%notes.length];tone(n,.28,'triangle',.022);if(i%4===0)tone(n/2,.45,'sine',.025,.03)},360)}
 function heartbeat(){if(!audioCtx)return;const speed=Math.max(.38,.95-state.doors*.06);tone(58,.12,'sine',.07);tone(48,.1,'sine',.045,speed*.22)}
function doorSound(){if(!audioCtx)return;const buffer=audioCtx.createBuffer(1,audioCtx.sampleRate*.45,audioCtx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*Math.pow(1-i/data.length,2);const src=audioCtx.createBufferSource(),filter=audioCtx.createBiquadFilter(),g=audioCtx.createGain();filter.type='lowpass';filter.frequency.value=850;g.gain.value=.12;src.buffer=buffer;src.connect(filter);filter.connect(g);g.connect(masterGain);src.start()}
function shacoLaugh(){const a=$('#shaco-laugh');if(!a)return;a.volume=.24;a.currentTime=0;a.play().catch(()=>{})}
function setText(){ $('#door-count').textContent=state.doors; $('#room-count').textContent=state.rooms; $('#threat-meter').textContent=`ATTENZIONE: ${state.threat}%`; $('#whisper').textContent=whispers[Math.min(Math.floor(state.doors/2),whispers.length-1)]; const game=$('#game');game.classList.remove('paranoia-1','paranoia-2','paranoia-3','paranoia-4');if(state.doors>=6)game.classList.add('paranoia-4');else if(state.doors>=4)game.classList.add('paranoia-3');else if(state.doors>=2)game.classList.add('paranoia-2');else if(state.doors>=1)game.classList.add('paranoia-1'); }
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2600)}
function makeDoor(i){const d=document.createElement('button');d.className='door';const id=`${state.rooms}-${i}-${state.doors}`;const isFalse=(state.doors>2&&Math.random()<.18);if(isFalse)d.classList.add('false-door');d.innerHTML=`<span class="door-knob"></span><span class="door-mark">${isFalse?'✶':'◈'}</span>`;d.addEventListener('click',()=>openDoor(d,id,isFalse));return d}
function spawnDoors(){const wrap=$('#doors');wrap.innerHTML='';const count=Math.min(6,3+Math.floor(state.doors/2));for(let i=0;i<count;i++)wrap.appendChild(makeDoor(i));}
function showShaco(){const s=$('#shaco-glimpse');s.classList.toggle('box-mode',Math.random()<.5);s.classList.add('show');shacoLaugh();tone(92,.65,'sawtooth',.035);setTimeout(()=>s.classList.remove('show'),850)}
function launchChaos(){if(state.chaos)return;state.chaos=true;setText();const room=$('#room');const storm=$('#door-storm');storm.innerHTML='';for(let i=0;i<18;i++){const d=document.createElement('div');d.className='storm-door';d.style.left=`${Math.random()*92}%`;d.style.top=`${Math.random()*82}%`;d.style.setProperty('--r',`${-18+Math.random()*36}deg`);d.style.animationDelay=`${Math.random()*420}ms`;storm.appendChild(d)}const flash=document.createElement('div');flash.className='storm-flash';document.body.appendChild(flash);setTimeout(()=>flash.remove(),300);$('#shaco-glimpse').classList.add('box-mode');room.classList.add('chaos');toast('Hai aperto troppe porte. Adesso tutte le porte sanno dove sei.');setTimeout(()=>{room.classList.remove('chaos');storm.innerHTML='';$('#shaco-glimpse').classList.remove('show','box-mode');start()},5200)}
function enterDoor(el){const actor=$('.character');const room=$('#room').getBoundingClientRect();const target=el.getBoundingClientRect();const baseX=room.left+room.width*.15;const dx=(target.left+target.width/2)-baseX;const from=getComputedStyle(actor).transform;const to=`translateX(calc(-50% + ${dx}px))`;actor.animate([{transform:from},{transform:to}],{duration:900,easing:'cubic-bezier(.2,.75,.2,1)',fill:'forwards'});actor.style.transform=to;actor.style.setProperty('--door-dx',`${dx}px`)}
function openDoor(el,id,isFalse){if(state.opened.has(id)||state.chaos)return;ensureAudio();doorSound();state.opened.add(id);state.doors++;heartbeat();state.threat=Math.min(100,state.threat+Math.floor(5+Math.random()*10));state.rooms++;enterDoor(el);if(isFalse){toast('La porta si è chiusa dietro di te. Ma non eri tu a chiuderla.');state.threat=Math.min(100,state.threat+12)}else if(state.doors===1)toast('Un corridoio nuovo. Le porte non diminuiscono.');else toast(Math.random()<.5?'Hai aperto una porta. Il pubblico applaude.':'Qualcuno ha cambiato posto alle pareti.');if(state.doors>=CHAOS_LIMIT){setTimeout(launchChaos,900);return}if(Math.random()<Math.min(.82,.18+state.doors*.08))setTimeout(showShaco,320);setTimeout(()=>{spawnDoors();setText()},850);setText()}
function start(){state.started=true;state.chaos=false;state.doors=0;state.rooms=1;state.threat=0;state.opened=new Set();ensureAudio();startCircusMusic();circusBell();$('#game').classList.add('music-tremble');$('#intro-panel').classList.add('hidden');$('#ending').classList.add('hidden');$('#play-area').classList.remove('hidden');$('#room').classList.remove('chaos');$('#door-storm').innerHTML='';$('#reset-card').style.opacity='';$('.character').style.transform='translateX(-50%)';$('.character').style.removeProperty('--door-dx');spawnDoors();setText()}
$('#start-btn').addEventListener('click',start);$('#again-btn').addEventListener('click',start);
window.addEventListener('keydown',e=>{if(e.key==='Escape')start()});
